### 난수(random number)

In [ ]:
'''
# 난수 발생 : np.rand() - 0부터 1사이의 실수
# seed(씨앗값) : 



'''

In [5]:
import numpy as np

In [2]:
np.random.seed(0)
np.random.rand(5)

array([0.5488135 , 0.71518937, 0.60276338, 0.54488318, 0.4236548 ])

In [3]:
np.random.rand(5)

array([0.64589411, 0.43758721, 0.891773  , 0.96366276, 0.38344152])

In [4]:
np.random.seed(0)
np.random.rand(5)

array([0.5488135 , 0.71518937, 0.60276338, 0.54488318, 0.4236548 ])

In [5]:
np.random.seed(2) # seed를 바꾸면 그때 그때 다른 난수사용가능
np.random.rand(5)

array([0.4359949 , 0.02592623, 0.54966248, 0.43532239, 0.4203678 ])

In [6]:
for i in range(10):
    print(np.random.rand())

0.3303348210038741
0.2046486340378425
0.6192709663506637
0.29965467367452314
0.26682727510286663
0.6211338327692949
0.5291420942770391
0.13457994534493356
0.5135781212657464
0.18443986564691528


In [7]:
np.random.rand(10)

array([0.78533515, 0.85397529, 0.49423684, 0.84656149, 0.07964548,
       0.50524609, 0.0652865 , 0.42812233, 0.09653092, 0.12715997])

In [8]:
# shuffle 
x = np.arange(10)
print(x)
print('------------------------')
np.random.shuffle(x)
print(x)

[0 1 2 3 4 5 6 7 8 9]
------------------------
[5 3 8 6 7 0 1 9 4 2]


In [ ]:
'''
# 데이터 샘플링 : 이미 있는 데이터 집합에서 무작위로 선택하는 것 (sampling)
# np.random.choice(원본데이터, size, replace=True/False, p)

- 원본 데이터 : 정수
- size : 샘플 숫자
-replace : True이면 한 번 선택한 데이터를 다시 선택할 수 있음
- p : 각 데이터가 선택될 수 있는 확률

'''

In [9]:
x = np.random.choice(5,5,replace=False); x

array([2, 3, 0, 4, 1])

In [12]:
x1 = np.random.choice(5,3,replace=False); x1

array([4, 3, 0])

In [13]:
x2 = np.random.choice(5,10,replace=False); x2

ValueError: Cannot take a larger sample than population when 'replace=False'

In [14]:
x2 = np.random.choice(5, 10, replace=True); x2 #replace=True : 재사용이 가능하다, 
# 재사용을 하면 원본데이터보다 더 많은 값 추출 가능

array([1, 1, 1, 4, 2, 3, 0, 3, 0, 2])

In [ ]:
x3 = np.random.choice(5, 10, replace=True, p=[0.1,0,0,0.3,0.6]); x3 # 요소별 선택 확률도 부여

In [ ]:
'''
# rand() : 0~1 실수 균일 분포
# randn() : 0~1 실수 가우시안 표준 정규 분포
# randint() : 균일분포 정수 - 난수
 - randint(low, high, size)
    -- size : 난수의 갯수
    
'''

In [15]:
np.random.rand(5)

array([0.31529748, 0.25873317, 0.80917529, 0.35367538, 0.46784249])

In [16]:
np.random.rand(3, 5)

array([[0.27417326, 0.79820039, 0.81413841, 0.94809042, 0.82288464],
       [0.51513912, 0.22099815, 0.74663141, 0.43153777, 0.88830375],
       [0.9411933 , 0.50301225, 0.70204204, 0.70654201, 0.48102176]])

In [18]:
np.random.randn(10)

array([-0.03957024,  0.32600343, -2.04032305,  0.04625552, -0.67767558,
       -1.43943903,  0.52429643,  0.73527958, -0.65325027,  0.84245628])

In [17]:
np.random.randint(10,50,5)

array([42, 26, 31, 39, 26])

In [29]:
# 로또번호 6개 구해보세요

np.random.randint(1,46,6)

array([23, 20, 32, 18,  9, 38])

In [4]:
# 로또 5천원 어치 구해보세요.

np.random.randint(1,46, [5,6])

array([[28, 37,  1, 20, 43, 19],
       [20,  2, 22, 25, 27, 38],
       [ 3, 45,  4, 23, 43, 30],
       [41, 40, 35, 11,  8,  3],
       [26, 40,  4, 19, 29, 43]])

In [3]:
# cf) 큰 값을 선언하지 않고 배열로 만드는 방법

np.empty((4, 3))


array([[1.39876089e-311, 3.16202013e-322, 0.00000000e+000],
       [0.00000000e+000, 4.00766127e+175, 9.96536156e-043],
       [1.51073576e+160, 6.82059259e-067, 3.14130502e-032],
       [1.24476417e-047, 1.57433965e+161, 1.16440535e+165]])