In [3]:
'''
# numpy 기술 통계(Descriptive statistics)
- 분산 (variance): 데이터와 샘플 평균간 거리의 제곱의 평균
                 : 이 값이 작으면 데이터가 모여 있는 것, 이 값이 크면 흩어져 있는 것
                 : np.var(x)
- 표준 편차(standard deviation): 분산의 제곱근 값.
                              : np.std(x)
- 최대값(maximum) : 데이터중에서 가장 큰 값 - np.max(x)
- 최소값(minimum) : 데이터 중에서 가장 적은 값 - np.min(x)
- 중앙값(median) : 데이터를 크기 대로 정렬하였을 때 가운데에 있는 수
                : 가장 가운데에 있는 수가 2개이면? 중앙 두 수의 평균을 사용
                : np.median(x)

- 사분위수(quartile) : 데이터를 크기대로 정렬하였을 때 1/4, 2/4, 3/4 위치에 있는 수
                    : 1사분위수, 2사분위수, 3사분위수 

                    : 데이터가 100개 라면 25번째 순서가 1사분위수 
                    : 위치를 1/100단위로 나눈 백분위수(percentile)를 사용하기도 함
                    이 때는 1사분위수는 25% 
                    : np.percentile(x, 0) # 최소값
                     : np.percentile(x, 25) # 1사분위수
                      : np.percentile(x, 50) # 2사분위수
                       : np.percentile(x, 75) # 3사분위수
                        : np.percentile(x, 100) # 최대값
                    
   - 합계 : np.sum()
   - 여러 개의 수를 연속하여 곱하기 : np.product()
'''

'\n# numpy 기술 통계(Descriptive statistics)\n- 분산 (variance): 데이터와 샘플 평균간 거리의 제곱의 평균\n                 : 이 값이 작으면 데이터가 모여 있는 것, 이 값이 크면 흩어져 있는 것\n                 : np.var(x)\n- 표준 편차(standard deviation): 분산의 제곱근 값.\n                              : np.std(x)\n- 최대값(maximum) : 데이터중에서 가장 큰 값 - np.max(x)\n- 최소값(minimum) : 데이터 중에서 가장 적은 값 - np.min(x)\n- 중앙값(median) : 데이터를 크기 대로 정렬하였을 때 가운데에 있는 수\n                : 가장 가운데에 있는 수가 2개이면? 중앙 두 수의 평균을 사용\n                : np.median(x)\n\n- 사분위수(quartile) : 데이터를 크기대로 정렬하였을 때 1/4, 2/4, 3/4 위치에 있는 수\n                    : 1사분위수, 2사분위수, 3사분위수 \n\n                    : 데이터가 100개 라면 25번째 순서가 1사분위수 \n                    : 위치를 1/100단위로 나눈 백분위수(percentile)를 사용하기도 함\n                    이 때는 1사분위수는 25% \n                    : np.percentile(x, 0) # 최소값\n                     : np.percentile(x, 0) # 최소값\n                      : np.percentile(x, 0) # 최소값\n                    \n'

In [4]:
import numpy as np

In [5]:
x = np.array([18, 5, 10, 2, 3, 11, -3, -5, -30, 15, 6, 78, -13, 9, 5, 6, 7]); x

array([ 18,   5,  10,   2,   3,  11,  -3,  -5, -30,  15,   6,  78, -13,
         9,   5,   6,   7])

In [6]:
len(x)

17

In [7]:
# 평균
np.mean(x)

7.294117647058823

In [8]:
# 분산
np.var(x)

430.4429065743944

In [9]:
# 표준편차
np.std(x)

20.747118030569798

In [11]:
# 최대값, 최소값
print(np.max(x))
print(np.min(x))
print(np.median(x))

78
-30
6.0


In [14]:
# 사분위수
print(np.percentile(x,0))
print(np.percentile(x,25))
print(np.percentile(x,50))
print(np.percentile(x,75))
print(np.percentile(x,100))



-30.0
2.0
6.0
10.0
78.0


In [15]:
# 합계
np.sum(x)

124

In [16]:
# 연속 곱
np.product(x)

-526923904

# 선형대수 

In [ ]:
'''
# 선형대수(linear algebra) : 데이터 분석에 필요한 여러 계산을 돕기 위한 학문
 > 데이터 유형 
 - 스칼라(scalar) : 하나의 숫자로 이루어진 데이터
 - 벡터(vector) : 여러 개의 숫자로 이루어진 데이터 (data record)
 - 행렬(maxtrix) : 벡터가 여러개 있는 데이터 집합
 

'''

In [17]:
import numpy as np

In [18]:
x = 1
x 

1

In [19]:
# 벡터
# numpy에서 벡터를 표현할 때 벡터를 열의 개수가 하나인 2차원 배열 객체로 표현하는 것을 권장

x = np.array([[2],[2],[3]])
x


array([[2],
       [2],
       [3]])

In [20]:
# 행렬
# 복수의 데이터 집합을 행렬로 표현

# 전치 행렬 : 행렬에서 가장 기본이 되는 연산 (행과 열을 바꾸는 연산)
#           : 전치 연산으로 만들어진 행렬을 원래 행렬에 대한 전치행렬이라고 부릅니다.



x = np.array([[2,2],[3,3],[4,4],[5,5]])
x

array([[2, 2],
       [3, 3],
       [4, 4],
       [5, 5]])

In [21]:
x.T # T 속성(Attribute)을 이용하여 전치 행렬을 적용. T가 메소드가 아님에 유의

array([[2, 3, 4, 5],
       [2, 3, 4, 5]])

In [22]:
x = np.array([[2],[2],[3]])
x

array([[2],
       [2],
       [3]])

In [23]:
x.T  # 벡터에 대한 전치 연산 결과는 행이 1개인 행렬

array([[2, 2, 3]])

In [24]:
x = np.array([2,2,3])
x


array([2, 2, 3])

In [25]:
x.T   # rank가 1인 ndarray는 전치 연산이 정의되지 않는다

array([2, 2, 3])

In [ ]:
'''
# 특수한 벡터와 행렬
# 0벡터 : 모든 원소가 0인 n차원 벡터
  일벡터 : 모든 원소가 1인 n차원 벡터
  
# 정방행렬(square matrix)
: 행의 개수와 열의 개수가 같은 행렬

# 대각행렬 : 모든 비대각 요소(off-diagonal)가 0인 정방 행렬
          : np.diag
          
  - 단위행렬 : 대각행렬 중에서 모든 대각요소(주요소)값이 1인 대각행렬 (identity matrix)
             : np.identity, np.eye
             
# 대칭행렬 : 전치 연산을 통해서 얻은 전치행렬과 원래의 행렬이 같은 경우 (sysmmetric matrix)
          : 정방행렬
          
'''

In [26]:
I = np.identity(3)

In [27]:
np.diag(I)

array([1., 1., 1.])

In [ ]:
'''
#벡터의 내적
#벡터의 공간에서 정의된 이중 선형(bilinear) 함수의 일종. inner product 또는 dot product라고 부름
# 행렬 곱셈의 결과행렬은 앞 행렬의 행벡터와 뒤 행렬의 열 벡터를 내적한 값을 스칼라로 가지는 행렬


'''

In [38]:
# 행렬
x = np.array([[1,2], [3,4]])
y = np.array([[5,6], [7,8]])

In [33]:
# 벡터
v = np.array([9,10])
w = np.array([11,12])

In [34]:
# 벡터의 내적
v.dot(w)

219

In [35]:
np.dot(v, w)

219

In [40]:
print(x)
print('-------------------')
print(v)

[[1 2]
 [3 4]]
-------------------
[ 9 10]


In [ ]:
# 매트릭스 벡터 내적
x.dot(v)

In [36]:
np.dot(x, v)

array([29, 67])

In [41]:
# 매트릭스 , 매트릭스 내적
x.dot(y)

array([[19, 22],
       [43, 50]])

In [42]:
np.dot(x,y)

array([[19, 22],
       [43, 50]])

### broadCasting

In [ ]:
'''
# ex)
1 2             + 10 10
3 4               10 10

# 브로드 캐스팅이 일어날 수 있는 조건
- 차원 크기가 1, 즉 스칼라면 가능
- 차원 크기가 1이 아니라면 차원의 짝이 맞는 조건 (축의 길이가 같을 때 등등)
'''

In [47]:
import numpy as np

In [49]:
a = np.array([[1,2],[3,4]])
a

array([[1, 2],
       [3, 4]])

In [50]:
b = 10

In [51]:
a + b  # 자동으로 브로드캐스팅이 적용된 상태

array([[11, 12],
       [13, 14]])

In [54]:
a = np.array([1,2,3,4])
b = np.array([1,2])

In [55]:
a + b

ValueError: operands could not be broadcast together with shapes (4,) (2,) 

In [56]:
x = np.arange(3)
y = 5

In [57]:
x + y 

array([5, 6, 7])

In [59]:
x = np.ones((3,3))
x

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [60]:
y = np.arange(3)
y

array([0, 1, 2])

In [61]:
x+y


array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])

In [ ]:
# 3차원 배열

In [64]:
d = np.array([[[1,2,3,4],
             [5,6,7,8],
             [9,10,11,12]],
             [[13,14,15,16],
             [17,18,19,20],
             [21,22,23,24]]])
d

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])

In [65]:
print(len(d)) # 깊이
print(len(d[0])) # 행
print(len(d[0][0])) # 열

2
3
4


In [66]:
# 1로 채운 3차원 배열
d = np.ones((2,3,4), dtype='i')
d

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int32)

In [67]:
# 다른 배열과 같은 형태의 배열을 만들고 싶을 때 : 
d2 = np.ones_like(d, dtype='f')
d2

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]], dtype=float32)

In [68]:
# 같은 형태 배열 : copy()
copy = np.copy(d); copy

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int32)

In [69]:
# 대입으로도 가능
copy2 = copy
copy2

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int32)

In [70]:
# 3차원도 브로드캐스팅 가능
d3 = np.ones((3,4,2))
d3

array([[[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]]])

In [71]:
d2 = np.array([[0,1],[2,3],[3,4],[5,6]])
d2

array([[0, 1],
       [2, 3],
       [3, 4],
       [5, 6]])

In [72]:
d3+d2

array([[[1., 2.],
        [3., 4.],
        [4., 5.],
        [6., 7.]],

       [[1., 2.],
        [3., 4.],
        [4., 5.],
        [6., 7.]],

       [[1., 2.],
        [3., 4.],
        [4., 5.],
        [6., 7.]]])